#!/bin/env bash

firstexec=0

function group_init() {
	
	./socat1 - UDP4-DATAGRAM:255.255.255.255:51423,broadcast,bind=:51423  | while read line; do
		
		if [[ $firstexec == 0 ]];then
			clear
			firstexec=1
			echo "Welcome to blackcat chatroom"
			read -p "insert yout username : " username
		else
	   		echo "[$username] $line" 
		fi

	done
}

group_init

