#!/bin/env bash


clear
firstexec=1
echo "Welcome to blackcat chatroom"
read -p "insert yout servername: " servername

function group_init() {
	
	user=$USER

	./socat1 - UDP4-DATAGRAM:255.255.255.255:51423,broadcast,bind=:51423  | while read -r line; do
		echo "[$user@$servername] $line" 
	done
}

group_init
